
name: AKS Deploy
on:
  workflow_call:
    inputs:
      appName:
        required: true
        type: string
      appEnv:
        required: true
        type: string
      resourceGroup:
        required: true
        type: string
    secrets:
      azuresecrets:
        required: true
jobs:
  Deploy:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Checkout Helm repo
        uses: actions/checkout@v4
        with:
          repository: golive123/roboshop-helm
          path: helm
      - name: Import Secrets
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault.yourtherapist.in:8200/
          method: token
          token: ${{ secrets.azuresecrets }}
          secrets: |
            kv/data/azuresecrets ARM_CLIENT_ID | ARM_CLIENT_ID ;
            kv/data/azuresecrets ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            kv/data/azuresecrets ARM_TENANT_ID | ARM_TENANT_ID ;
            kv/data/azuresecrets ARM_SUBSCRIPTION_ID | ARM_SUBSCRIPTION_ID
      - name: Deploy
        run: |
          cd helm
          az login --service-principal --username "${ARM_CLIENT_ID}" --password "${ARM_CLIENT_SECRET}" --tenant "${ARM_TENANT_ID}"
          az aks get-credentials --name main-${{ inputs.appEnv }} --resource-group ${{ inputs.resourceGroup }} --overwrite-existing
          helm upgrade -i ${{ inputs.appName }} . -f env-${{ inputs.appEnv }}/${{ inputs.appName }}.yaml -n app --create-namespace --set appTag=${{ github.sha }}
