name: CI ReUse Dev
on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string
      docker_build:
        required: true
        type: string
    secrets:
      azuresecrets:
        required: true
jobs:
  Build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: npm install
        name: Download NodeJS Dependencies
        if: inputs.appType == 'nodejs'
      - run: mvn package
        name: Download Maven Dependencies
        if: inputs.appType == 'maven'
      - name: Import Secrets
        if: inputs.docker_build == 'true'
        id: import-secrets
        uses: hashicorp/vault-action@v2
        with:
          url: http://vault.yourtherapist.in:8200/
          method: token
          token: ${{ secrets.azuresecrets }}
          secrets: |
            kv/data/azuresecrets ARM_CLIENT_ID | ARM_CLIENT_ID ;
            kv/data/azuresecrets ARM_CLIENT_SECRET | ARM_CLIENT_SECRET ;
            kv/data/azuresecrets ARM_TENANT_ID | ARM_TENANT_ID ;
            kv/data/azuresecrets ARM_SUBSCRIPTION_ID | ARM_SUBSCRIPTION_ID
      - name: Docker Build
        if: inputs.docker_build == 'true'
        run: |
          az login --service-principal --username "$ARM_CLIENT_ID" --password "$ARM_CLIENT_SECRET" --tenant "$ARM_TENANT_ID"
          az acr login --name golive
          docker build -t golive.azurecr.io/roboshop-${{ inputs.appName }}:${{ github.sha }} .
          docker push golive.azurecr.io/roboshop-${{ inputs.appName }}:${{ github.sha }}
