name: CI Reuse Main

on:
  workflow_call:
    inputs:
      appType:
        required: true
        type: string
      appName:
        required: true
        type: string
    secrets:
      azuresecrets:
        required: true

jobs:
  Build:
    uses: golive123/roboshop-github-actions/.github/workflows/ci-build.yml@main
    with:
      appType: '${{ inputs.appType }}'
      appName: '${{ inputs.appName }}'
      docker_build: "false"
    secrets:
      azuresecrets: ${{ secrets.AZURESECRETS }}

  Test:
    needs: Build
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - run: |
          echo npm install
          echo npm test
        name: Run NodeJS Tests
        if: inputs.appType == 'nodejs'
      - run: echo mvn test
        name: Run Maven Tests
        if: inputs.appType == 'maven'
      - run: echo python -m unittest
        name: Run Python Tests
        if: inputs.appType == 'python'

  Docker_build:
    needs: Test
    uses: golive123/roboshop-github-actions/.github/workflows/ci-build.yml@main
    with:
      appType: '${{ inputs.appType }}'
      appName: '${{ inputs.appName }}'
      docker_build: "true"
    secrets:
      azuresecrets: ${{ secrets.AZURESECRETS }}

  Dev_deploy:
    environment: Dev
    runs-on: ubuntu-latest
    needs: Docker_build
    steps:
      - run: echo "Deploying to Dev"

  Qa_Deploy:
    environment: QA
    runs-on: ubuntu-latest
    needs: Dev_deploy
    steps:
      - run: echo "Deploying to QA"

  Uat_Deploy:
    environment: UAT
    runs-on: ubuntu-latest
    needs: Qa_Deploy
    steps:
      - run: echo "Deploying to UAT"

  Prod_Deploy:
    environment: PROD
    runs-on: ubuntu-latest
    needs: Uat_Deploy
    steps:
      - run: echo "Deploying to PROD"
